### ISSUE TITLE
edit time table not working

### ISSUE THREAD

**Issue by ervinayakpatil** [pundliksarafdar/code#79] opened 2016-03-29 18:38 UTC
name : classowner2
psswd : Passwd@123
module name : time table
role : owner

issue : not able to edit time table correctly

**Comment by ervinayakpatil** [comment] 2016-04-03 18:28
1. its working only for month view. 
2. teacher for edit is not getting fetched

**Comment by ervinayakpatil** [comment] 2016-05-08 15:51
delete time table not working

**Comment by pundliksarafdar** [comment] 2016-06-12 07:20
Teacher is not fetch is duplicate of #84

**Closed as completed** 2016-07-10 15:28 UTC
Labels: bug, duplicate, fixed
